//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoShieldApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Purchase = new HashSet<Purchase>();
            this.ServiceOfProductInOrder = new HashSet<ServiceOfProductInOrder>();
            this.Worker = new HashSet<Worker>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public System.DateTime DateTimeOfCreate { get; set; }
        public Nullable<System.DateTime> DateTimeOfWork { get; set; }
        public int StatusOfOrderId { get; set; }
        public Nullable<System.DateTime> DateTimeOfEnd { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual StatusOfOrder StatusOfOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOfProductInOrder> ServiceOfProductInOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Worker> Worker { get; set; }
    }
}
