//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoShieldApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceOfProductInOrder = new HashSet<ServiceOfProductInOrder>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeOfServiceId { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
    
        public virtual TypeOfService TypeOfService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceOfProductInOrder> ServiceOfProductInOrder { get; set; }
    }
}
